servers:
  - name: fs
    type: docker
    image: ghcr.io/modelcontextprotocol/servers/filesystem:latest
    env: { ROOT: "/data" }
    mounts:
      - type: bind
        source: /mnt/data
        target: /data
  - name: web
    type: docker
    image: ghcr.io/modelcontextprotocol/servers/web:latest
  - name: github
    type: docker
    image: ghcr.io/modelcontextprotocol/servers/github:latest
    env:
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
  - name: postgres
    type: docker
    image: ghcr.io/modelcontextprotocol/servers/postgres:latest
    env:
      DATABASE_URL: "${POSTGRES_DSN}"
