A0: { description: "Read-only", allow_tools: ["rag.search"], auto_threshold: 0 }
A1: { description: "Draft-only", allow_tools: ["rag.search","draft.email","draft.doc","ticket.create"], auto_threshold: 1 }
A2: { description: "Low-risk", allow_tools: ["crm.update","calendar.schedule","ticket.update"], auto_threshold: 2 }
A3: { description: "Medium-risk", allow_tools: ["deploy.staging","experiment.launch"], auto_threshold: 3 }
A4: { description: "High autonomy", allow_tools: ["invoice.issue","vendor.po.create"], auto_threshold: 4 }
A5: { description: "Org-scale", allow_tools: ["*"], auto_threshold: 5 }
